[package]
name = "challenge6"
version = "0.1.0"
authors = ["Chris McDonald <mail.chris.mcdonald@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
cryptobuddy = {path = "../../cryptobuddy/"}
ordered-float = "0.2.3"
